const fs = require("fs");
const path = require("path");
const cp = require("child_process");
const { success, error, info, warn } = require("./logs");

const arch = process.argv.includes("--x64") ? "x64" : process.argv.includes("--arm64") ? "arm64" : process.arch;

function performNativeBuild() {


  let buildingForWindows = process.argv.includes("--windows") || process.argv.includes("--w");
  let buildingForMac = process.argv.includes("--mac") || process.argv.includes("--m");


  const appRoot = process.cwd(); // The developer's project folder
  const nativeExtensionsMac = [];
  const nativeExtensionsWindows = [];
  
  // 1. Discover Extensions from the developer's package.json
  const rootPackagePath = path.join(appRoot, "package.json");
  if (!fs.existsSync(rootPackagePath)) return false;

  const rootPackage = JSON.parse(fs.readFileSync(rootPackagePath, "utf8"));
  const dependencies = Object.keys(rootPackage.dependencies || {});

  for (const dep of dependencies) {
    const depPackagePath = path.join(appRoot, "node_modules", dep, "package.json");
    if (fs.existsSync(depPackagePath)) {
      const depPackage = JSON.parse(fs.readFileSync(depPackagePath, "utf8"));
      if (depPackage.positron) {
        const depDir = path.dirname(depPackagePath);

          let missing = [];
          if(!depPackage.positron.className) missing.push("className");
          if(!depPackage.positron.command) missing.push("command");
          if(!depPackage.positron.platforms) missing.push("platforms");
          else {
            if(!depPackage.positron.platforms.darwin) missing.push("platforms.darwin");
            if(!depPackage.positron.platforms.win32) missing.push("platforms.win32");
          }
          
          if(missing.includes("className") || missing.includes("command") || missing.includes("platforms")) {
            warn(`[Builder] Dependency "${dep}" has an invalid positron field. Missing: ${missing.join(", ")}. Skipping native extension build for this dependency.`);
            continue;
          }
        
        if(!missing.includes("platforms.darwin")) {
        nativeExtensionsMac.push({
          className: depPackage.positron.className, 
          command: depPackage.positron.command,
          sourceFile: path.join(depDir, depPackage.positron.platforms.darwin)
        });
      } else {
        warn(`[Builder] Dependency "${dep}" is missing a macOS platform source file. Skipping macOS native extension build for this dependency.`);
      }
      if(!missing.includes("platforms.win32")) {
        nativeExtensionsWindows.push({
          className: depPackage.positron.className, 
          command: depPackage.positron.command,
          sourceFile: path.join(depDir, depPackage.positron.platforms.win32)
        });
      } else {
        warn(`[Builder] Dependency "${dep}" is missing a Windows platform source file. Skipping Windows native extension build for this dependency.`);
      }
      }
    }
  }

  if(buildingForWindows == false && buildingForMac == false) {
    if (process.platform === "win32") {
      buildingForWindows = true;
    } else if (process.platform === "darwin") {
      buildingForMac = true;
    } else {
      error("[Builder] Unsupported platform for native build.");
      return false;
    }
  }

  if (buildingForMac) {
    info(`[Builder] Stitching ${nativeExtensionsMac.length} native extensions...`);
  
        let registryContent = `// Auto-generated by Positron. Do not edit.\n`;
    registryContent += `func getExtensionRegistry() -> [String: (Int, [String]) -> Void] {\n`;
    
    if (nativeExtensionsMac.length === 0) {
      registryContent += `    return [:]\n`;
    } else {
      registryContent += `    return [\n`;
      
      nativeExtensionsMac.forEach((ext, index) => {

         const comma = index === nativeExtensionsMac.length - 1 ? "" : ",";
         registryContent += `        "${ext.command}": ${ext.className}.handle${comma}\n`;
      });
      
      registryContent += `    ]\n`;
    }
    
    registryContent += `}\n`;
    
    const coreMacDir = path.join(__dirname, "core", "mac");
    fs.writeFileSync(path.join(coreMacDir, "Registry.swift"), registryContent);

    info("[Builder] Compiling native binary...");
    const outBinaryDir = path.join(appRoot, "bin");
    if (!fs.existsSync(outBinaryDir)) fs.mkdirSync(outBinaryDir, { recursive: true });

    const binaryName = "positron-runtime";
    const extensionSources = nativeExtensionsMac.map(e => e.sourceFile);
    
    let addedFrameworksSet = new Set();

    nativeExtensionsMac.forEach(ext => {
      if (ext.macFrameworks && Array.isArray(ext.macFrameworks)) {
        ext.macFrameworks.forEach(fw => {
          addedFrameworksSet.add(fw);
        });
      }
    });
    
    let addedFrameworksArgs = [];
    addedFrameworksSet.forEach(fw => {
      addedFrameworksArgs.push("-framework", fw);
    });

    try {
      cp.execFileSync("swiftc", [
        path.join(coreMacDir, "main.swift"),
        path.join(coreMacDir, "Registry.swift"),
        ...extensionSources,
        "-o", path.join(outBinaryDir, binaryName),
        "-framework", "Cocoa",
        "-framework", "WebKit",
        ...addedFrameworksArgs
      ]);
      success("[Builder] Native compilation successful.");

          if(process.platform == "darwin") {
      cp.execFile("chmod", ["+x", path.join(outBinaryDir, binaryName)], (err) => {
        if (err) {
          error("Failed to set executable permissions on native binary:", err);
        }
      });

      try {
        const iconPathEscaped = path.join(__dirname, "positronicon.png").replace(/"/g, '\\"');
        const binPathEscaped = path.join(outBinaryDir, binaryName).replace(/"/g, '\\"');
        const swiftScript = `import Cocoa; NSWorkspace.shared.setIcon(NSImage(contentsOfFile: "${iconPathEscaped}"), forFile: "${binPathEscaped}", options: [])`;
        cp.execFileSync("swift", ["-e", swiftScript], { stdio: "ignore" });
      } catch (err) {
        error("Failed to set custom icon on native binary:", err);
      }
    }

      return true;
    } catch (err) {
      error("[Builder] Compilation failed:", err.message);
      return false;
    }
    } 
    
    
     if (buildingForWindows) {
    info(`[Builder] Stitching ${nativeExtensionsWindows.length} native Windows extensions...`);

    const coreWinDir = path.join(__dirname, "core", "win");
    const extensionsDir = path.join(coreWinDir, "extensions");

    // 1. Clean and prepare a staging folder for all native extensions
    if (fs.existsSync(extensionsDir)) fs.rmSync(extensionsDir, { recursive: true, force: true });
    fs.mkdirSync(extensionsDir, { recursive: true });

    let registryContent = `// Auto-generated by Positron. Do not edit.\n`;
    registryContent += `using System;\nusing System.Collections.Generic;\n\n`;
    registryContent += `namespace PositronWindows {\n`;
    registryContent += `    public static class ExtensionRegistry {\n`;
    registryContent += `        public static Dictionary<string, Action<int, List<string>>> GetExtensions() {\n`;
    registryContent += `            return new Dictionary<string, Action<int, List<string>>> {\n`;

    nativeExtensionsWindows.forEach((ext, index) => {
        const comma = index === nativeExtensionsWindows.length - 1 ? "" : ",";
        registryContent += `                { "${ext.command}", ${ext.className}.Handle }${comma}\n`;

        const destFile = path.join(extensionsDir, `ext_${index}.cs`);
        fs.copyFileSync(ext.sourceFile, destFile);
    });

    registryContent += `            };\n`;
    registryContent += `        }\n`;
    registryContent += `    }\n}\n`;

    fs.writeFileSync(path.join(extensionsDir, "Registry.cs"), registryContent);

    info("[Builder] Compiling Windows native binary via .NET CLI...");
    const outBinaryDir = path.join(appRoot, "bin");
    if (!fs.existsSync(outBinaryDir)) fs.mkdirSync(outBinaryDir, { recursive: true });

    try {

      const iconPath = path.join(appRoot, "icon.ico");
      const dotnetArgs = [
        "publish",
        path.join(coreWinDir, "PositronRuntime.csproj"),
        "-c", "Release",
        "-r", `win-${arch}`,
        "--self-contained", "true",
        "-o", outBinaryDir,
        "/p:PublishSingleFile=true",
        "/p:IncludeNativeLibrariesForSelfContained=true"
      ];
      if (fs.existsSync(iconPath)) {
        dotnetArgs.push(`/p:ApplicationIcon=${iconPath}`);
      }

      cp.execFileSync("dotnet", dotnetArgs, { stdio: "inherit" });
      success("[Builder] Windows native compilation successful.");
      return true;
    } catch (err) {
      error("[Builder] Windows compilation failed:", err.message);
      return false;
    }
  }
  
  return false; // Unsupported platform
 
}

module.exports = { performNativeBuild };