// positron-core/builder.js
const fs = require("fs");
const path = require("path");
const cp = require("child_process");
const { success, error, info } = require("./logs");

function performNativeBuild() {


  let buildingForWindows = process.argv.includes("--windows") || process.argv.includes("--w");
  let buildingForMac = process.argv.includes("--mac") || process.argv.includes("--m");


  const appRoot = process.cwd(); // The developer's project folder
  const nativeExtensionsMac = [];
  const nativeExtensionsWindows = [];
  
  // 1. Discover Extensions from the developer's package.json
  const rootPackagePath = path.join(appRoot, "package.json");
  if (!fs.existsSync(rootPackagePath)) return false;

  const rootPackage = JSON.parse(fs.readFileSync(rootPackagePath, "utf8"));
  const dependencies = Object.keys(rootPackage.dependencies || {});

  for (const dep of dependencies) {
    const depPackagePath = path.join(appRoot, "node_modules", dep, "package.json");
    if (fs.existsSync(depPackagePath)) {
      const depPackage = JSON.parse(fs.readFileSync(depPackagePath, "utf8"));
      if (depPackage.positron) {
        const depDir = path.dirname(depPackagePath);
        nativeExtensionsMac.push({
          className: depPackage.positron.className, 
          command: depPackage.positron.command,
          sourceFile: path.join(depDir, depPackage.positron.platforms.darwin)
        });
        nativeExtensionsWindows.push({
          className: depPackage.positron.className, 
          command: depPackage.positron.command,
          sourceFile: path.join(depDir, depPackage.positron.platforms.win32)
        });
      }
    }
  }

  if(buildingForWindows == false && buildingForMac == false) {
    if (process.platform === "win32") {
      buildingForWindows = true;
    } else if (process.platform === "darwin") {
      buildingForMac = true;
    } else {
      error("[Builder] Unsupported platform for native build.");
      return false;
    }
  }

  if (buildingForMac) {
    info(`[Builder] Stitching ${nativeExtensionsMac.length} native extensions...`);
  
        let registryContent = `// Auto-generated by Positron. Do not edit.\n`;
    registryContent += `func getExtensionRegistry() -> [String: (Int, [String]) -> Void] {\n`;
    
    if (nativeExtensionsMac.length === 0) {
      registryContent += `    return [:]\n`;
    } else {
      registryContent += `    return [\n`;
      
      nativeExtensionsMac.forEach((ext, index) => {

         const comma = index === nativeExtensionsMac.length - 1 ? "" : ",";
         registryContent += `        "${ext.command}": ${ext.className}.handle${comma}\n`;
      });
      
      registryContent += `    ]\n`;
    }
    
    registryContent += `}\n`;
    
    const coreMacDir = path.join(__dirname, "core", "mac");
    fs.writeFileSync(path.join(coreMacDir, "Registry.swift"), registryContent);

    info("[Builder] Compiling native binary...");
    const outBinaryDir = path.join(appRoot, "bin");
    if (!fs.existsSync(outBinaryDir)) fs.mkdirSync(outBinaryDir, { recursive: true });

    const binaryName = "positron-runtime";
    const extensionSources = nativeExtensionsMac.map(e => e.sourceFile).join(" ");
    
    let addedFrameworks = []

    nativeExtensionsMac.forEach(ext => {
      if (ext.macFrameworks && Array.isArray(ext.macFrameworks)) {
        ext.macFrameworks.forEach(fw => {
          if (!addedFrameworks.includes(fw)) {
            addedFrameworks.push(`-framework ${fw}`);
          }
        });
      }
    });

    try {
      cp.execSync(
        `swiftc ${path.join(coreMacDir, "main.swift")} ${path.join(coreMacDir, "Registry.swift")} ${extensionSources} -o ${path.join(outBinaryDir, binaryName)} -framework Cocoa -framework WebKit ${addedFrameworks.join(" ")}`,
      );
      success("[Builder] Native compilation successful.");

          if(process.platform == "darwin") {
      cp.exec(`chmod +x "${path.join(outBinaryDir, binaryName)}"`, (err) => {
        if (err) {
          error("Failed to set executable permissions on native binary:", err);
        }
      });

      cp.execSync(`swift -e 'import Cocoa; NSWorkspace.shared.setIcon(NSImage(contentsOfFile: "${path.join(__dirname, "positronicon.png")}"), forFile: "${path.join(outBinaryDir, binaryName)}", options: [])'`);
    }

      return true;
    } catch (err) {
      error("[Builder] Compilation failed:", err.message);
      return false;
    }
    } 
    
    
     if (buildingForWindows) {
    info(`[Builder] Stitching ${nativeExtensionsWindows.length} native Windows extensions...`);

    const coreWinDir = path.join(__dirname, "core", "win");
    const extensionsDir = path.join(coreWinDir, "extensions");

    // 1. Clean and prepare a staging folder for all native extensions
    if (fs.existsSync(extensionsDir)) fs.rmSync(extensionsDir, { recursive: true, force: true });
    fs.mkdirSync(extensionsDir, { recursive: true });

    let registryContent = `// Auto-generated by Positron. Do not edit.\n`;
    registryContent += `using System;\nusing System.Collections.Generic;\n\n`;
    registryContent += `namespace PositronWindows {\n`;
    registryContent += `    public static class ExtensionRegistry {\n`;
    registryContent += `        public static Dictionary<string, Action<int, List<string>>> GetExtensions() {\n`;
    registryContent += `            return new Dictionary<string, Action<int, List<string>>> {\n`;

    nativeExtensionsWindows.forEach((ext, index) => {
        const comma = index === nativeExtensionsWindows.length - 1 ? "" : ",";
        registryContent += `                { "${ext.command}", ${ext.className}.Handle }${comma}\n`;

        // 2. Copy the external dependency .cs file into our local staging folder
        // We use an index prefix just in case two plugins have a file named "main.cs"
        const destFile = path.join(extensionsDir, `ext_${index}.cs`);
        fs.copyFileSync(ext.sourceFile, destFile);
    });

    registryContent += `            };\n`;
    registryContent += `        }\n`;
    registryContent += `    }\n}\n`;

    fs.writeFileSync(path.join(extensionsDir, "Registry.cs"), registryContent);

    info("[Builder] Compiling Windows native binary via .NET CLI...");
    const outBinaryDir = path.join(appRoot, "bin");
    if (!fs.existsSync(outBinaryDir)) fs.mkdirSync(outBinaryDir, { recursive: true });

    try {
      let cmd = `dotnet publish "${path.join(coreWinDir, "PositronRuntime.csproj")}" ` +
                `-c Release -r win-x64 --self-contained true -o "${outBinaryDir}" ` +
                `/p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfContained=true`;

      cp.execSync(cmd, { stdio: "inherit" });
      success("[Builder] Windows native compilation successful.");
      return true;
    } catch (err) {
      error("[Builder] Windows compilation failed:", err.message);
      return false;
    }
  }
  
  return false; // Unsupported platform
 
}

module.exports = { performNativeBuild };